# version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - elasticsearch
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

 