# version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5433:5432" # Host:Container, changing host port to 5433
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - elasticsearch
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend


